import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'My One Book',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="max-w-2xl min-h-screen mx-auto my-0 bg-white py-0 px-4 shadow-[rgba(100,100,111,0.2)_0px_7px_29px_0px]">
          <header className="h-16 font-bold text-lg leading-[60px]">
            <Link href="/">📚 ONEBITE BOOKS</Link>
          </header>
          <main className="py-3">{children}</main>
          <footer className="py-24 text-gray-600">제작 @bora</footer>
        </div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
